version: 2
jobs:
  build_and_test:
    working_directory: ~/best

    docker:
      - image: circleci/node:8.9.3-stretch-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-v3-{{ .Branch }}-{{ checksum "package.json" }}
          - yarn-v3-{{ .Branch }}-

      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn test

      - save_cache:
          paths:
            - node_modules
            - packages/*/node_modules
            - examples/*/node_modules
            - yarn.lock
          key: yarn-v3-{{ .Branch }}-{{ checksum "package.json" }}

<<<<<<< HEAD
  perf_and_compare:
=======
  unit_test:
    working_directory: ~/best

    docker:
      - image: circleci/node:8.9.3-stretch-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-v3-{{ .Branch }}-{{ checksum "package.json" }}
          - yarn-v3-{{ .Branch }}-

      - run: yarn install

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Unit Test
          command: yarn test

  perf_test:
    working_directory: ~/best

    docker:
      - image: circleci/node:8.9.3-stretch-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-v3-{{ .Branch }}-{{ checksum "package.json" }}
          - yarn-v3-{{ .Branch }}-

      - run: yarn install
      - run: yarn build
      - run:
          name: Performance Test - Example project
          command: yarn perf:example

  compare_perf:
>>>>>>> Fix yml indent
    working_directory: ~/best

    docker:
      - image: circleci/node:8.9.3-stretch-browsers

    environment:
      - CUSTOM_BASH_ENV: ~/.bashrc
      - CIRCLE_ENV_BROKEN: $CIRCLE_SHA1
      - PATH_GIT_APP_CERT: ~/best/git_app.pem

    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-v3-{{ .Branch }}-{{ checksum "package.json" }}
          - yarn-v3-{{ .Branch }}-

      - run:
          name: Setup dynamic environment variables
          command:
              echo '
              export PATH=./node_modules/.bin:$PATH
              export PULL_REQUEST=${CIRCLE_PULL_REQUEST}
              export REPO_NAME=${CIRCLE_PROJECT_REPONAME}
              export TARGET_COMMIT=${CIRCLE_SHA1}
              export BASE_COMMIT=`git rev-parse origin/master`' >> $BASH_ENV

      - run:
          name: Decode PEM as environment variable
          command: echo -e "$GIT_APP_CERT" | base64 -d >> ~/best/git_app.pem

      - run: yarn install
      - run: yarn build

      - run:
          name: Performance Test - Example project
          command: yarn perf:example

      - run:
          name: Comparing perf examples
          command: cd examples/simple_benchmark/ && best --compareStats ${BASE_COMMIT} ${TARGET_COMMIT} --externalStorage=@best/store-aws --gitIntegration

workflows:
  version: 2
  main_workflow:
    jobs:
      - build_and_test
      - perf_and_compare:
          requires:
            - build_and_test
