version: 2.1

executors:
  best-executor:
    docker:
      - image: circleci/node:10.16.0-stretch-browsers
    working_directory: ~/best

jobs:
  build_and_test:
    executor: best-executor
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-v3-{{ checksum "yarn.lock" }}

      - run: yarn install --frozen-lockfile
      - run:
          name: Sanity checks
          command: |
            node ./scripts/tasks/check-license-headers.js
      - run: yarn lint
      - run: yarn test

      - save_cache:
          paths:
            - ~/.cache/yarn
            - yarn.lock
            - node_modules
            - packages/*/node_modules
            - examples/*/node_modules
          key: yarn-v3-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: .
          paths: ./*

  perf_and_compare:
    executor: best-executor
    
    environment:
      - CUSTOM_BASH_ENV: ~/.bashrc
      - CIRCLE_ENV_BROKEN: $CIRCLE_SHA1
      - GIT_APP_CERT_PATH: ~/best/git_app.pem

    steps:
      - attach_workspace:
          at: .
      
      - checkout

      - run:
          name: Setup dynamic environment variables
          command:
              echo '
              export PATH=./node_modules/.bin:$PATH
              export PULL_REQUEST=${CIRCLE_PULL_REQUEST}
              export REPO_NAME=${CIRCLE_PROJECT_REPONAME}
              export TARGET_COMMIT=${CIRCLE_SHA1}
              export BASE_COMMIT=`git rev-parse origin/master`' >> $BASH_ENV

      - run:
          name: Decode PEM as environment variable
          command: echo -e "$GIT_APP_CERT" | base64 -d >> ~/best/git_app.pem

      - run:
          name: Run BEST Benchmarks
          command: yarn perf --runner heroku-hub --dbAdapter=sql/postgres --dbURI=${BEST_HUB_DATABASE_URL}
      - run:
          name: Compare BEST Benchmarks
          command: yarn perf --compareStats ${BASE_COMMIT} ${TARGET_COMMIT} --gitIntegration

workflows:
  main_workflow:
    jobs:
      - build_and_test
      - perf_and_compare:
          requires:
            - build_and_test
