version: 2
jobs:
  build:
    working_directory: ~/best

    docker:
      - image: circleci/node:8.9.3-stretch-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-v3-{{ .Branch }}-{{ checksum "package.json" }}
          - yarn-v3-{{ .Branch }}-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - packages/*/node_modules
            - examples/*/node_modules
            - yarn.lock
          key: yarn-v3-{{ .Branch }}-{{ checksum "package.json" }}

  unit_test:
    working_directory: ~/best

    docker:
      - image: circleci/node:8.9.3-stretch-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-v3-{{ .Branch }}-{{ checksum "package.json" }}
          - yarn-v3-{{ .Branch }}-

      - run: yarn install

      - run:
          name: Unit Test
          command: yarn test

  perf_test:
    working_directory: ~/best

    docker:
      - image: circleci/node:8.9.3-stretch-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-v3-{{ .Branch }}-{{ checksum "package.json" }}
          - yarn-v3-{{ .Branch }}-

      - run: yarn install
      - run: yarn build
      - run:
          name: Performance Test - Example project
          command: yarn perf:example

  compare_perf:
    working_directory: ~/best

    docker:
      - image: circleci/node:8.9.3-stretch-browsers

    environment:
      - CUSTOM_BASH_ENV: ~/.bashrc
      - CIRCLE_ENV_BROKEN: $CIRCLE_SHA1

    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-v3-{{ .Branch }}-{{ checksum "package.json" }}
          - yarn-v3-{{ .Branch }}-

      - run:
          name: Make Composer executables available globally
          command:
              echo '
              export PATH=./node_modules/.bin:$PATH
              export TARGET_COMMIT=${CIRCLE_SHA1}
              export PATH_GIT_APP_CERT=~/best/git_app.pem
              export BASE_COMMIT=`git rev-parse origin/master`' >> $BASH_ENV

      - run:
          name: Decode PEM as environment variable
          command: echo -e "$GIT_APP_CERT" | base64 -d >> ~/best/git_app.pem

      - run: yarn install
      - run: yarn build
      - run:
          name: Comparing perf examples
          command: cd examples/simple_benchmark/ && best --compareStats d46ad97 320b079 --externalStorage=@best/store-aws --gitIntegration

workflows:
  version: 2
  main_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - /\w+\/.*/

      - unit_test:
          requires:
            - build
          filters:
            branches:
              only: /\w+\/.*/

      - perf_test:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - /\w+\/.*/

      - compare_perf:
          requires:
            - perf_test
          filters:
            branches:
              only:
                - /\w+\/.*/
